# Generated by Django 3.0 on 2024-11-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0004_auto_20241124_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decreasestock',
            name='quantity',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='quantity',
            field=models.IntegerField(max_length=255),
        ),
    ]
